version: '3.9'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  bot:
    env_file: ".env"
    build: ./bot
    depends_on:
      - redis

  tracker:
    env_file: ".env"
    build: ./tracker
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis
      - proxy_pool
      - bot

  proxy_pool:
    image: jhao104/proxy_pool:latest
    ports:
      - "5555:5555"
    environment:
      - DB_CONN=redis://redis:6379
      - PORT=5555
    restart: always
